#!/bin/sh
#
# Hook used to indent all source files before commiting
#

ASTYLE="$(git config hooks.astyle)"
if test ! -x "$ASTYLE"
then
	echo "Unable to find astyle executable on the configuration."
	echo
	echo "Please configure it with :"
	echo "  git config hooks.astyle /path/to/astyle"
	echo
fi

# indent / format file by type
indent() {
	# getting against as the current commit
	if git rev-parse --verify HEAD >/dev/null 2>&1
	then
		local against=HEAD
	else
		# Initial commit: diff against an empty tree object
		local against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
	fi

	# loop on modified files
	git diff --cached --name-only $against |while read file;
	do
		local ext=$(expr "$file" : ".*\(\..*\)")
		case $ext in
		.cpp|.hpp)
			__indent_CPP;
		;;
		esac
	done
}

# Indent the file with `indent' if this is a C/H file
__indent_CPP() {
	if test ! -x "$ASTYLE"
	then
		return;
	fi
	if test ! -f $file
	then
		return;
	fi

	echo "Indenting " $file
	"$ASTYLE" --style=gnu --indent=tab "$file"
	git add "$file"
}

indent